### ISSUE TITLE
Template network contextualization doesn't work with Open Nebula 6.8.0 and RHEL9

### ISSUE THREAD

**Issue by jschoewe** [OpenNebula/one-apps#119]
**Description**
We're trying to instantiate a RHEL 9 template with a static IP. We installed the context packages onto the template according to this: https://github.com/OpenNebula/one-apps/wiki/linux_installation. RHEL 9 uses NetworkManager by default. The hostnames and static IPs show up just fine after instantiating, however, the gateway and DNS servers never get set. I've attached a picture of the template variables, I've tried every combination of params that I can think of in here, including removing NETWORK = "YES" and setting each ETH0 param manually and the DNS servers never get set.

**To Reproduce**
Instantiate template with static IP
![](https://opennebula.zendesk.com/attachments/token/9OE1xOmxQX7vOxS9r4P4scGZB/?name=Screenshot+2024-06-11+at+10.25.01%E2%80%AFAM.png)

![](https://opennebula.zendesk.com/attachments/token/6js5kqzYocUtsxp3D0xqkVHes/?name=Screenshot+2024-06-11+at+10.34.46%E2%80%AFAM.png)

**Expected behavior**
The given DNS servers should be associated with the network interface. 

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.8.0

**Additional context**
I opened support case 54333 for this issue and it was prematurely closed. The following workaround was given:
In Sunstone:
- Go to the Virtual Networks page
- Select the network that you want to use (ID 12)
- Click on "Update" and navigate to the "Context" tab
- Modify the Gateway and DNS parameters and click "Update"

While this does work, manually updating every network object if our DNS servers ever change is not a viable long-term solution. This is also not documented anywhere, including the known issues page, so this issue is needed for visibility in case others experience the same issue.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
OK, re-reading closing this issue and address this as part of the other ones already opened.
